name: Assign Rule IDs and Update Metadata

on:
  push:
    paths:
      - "rules/**/*.md"

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug File Detection
        run: |
          echo "Files changed in this commit:"
          git diff --name-only HEAD~1 HEAD

      - name: Assign Rule IDs and Add Last Modified Date
        run: |
          for file in $(git diff --diff-filter=A --name-only HEAD~1 HEAD | grep "rules/.*.md"); do
            echo "Processing file: $file"

            id=$(uuidgen | cut -c 1-8)
            last_modified=$(git log -1 --format="%ad" --date=short -- $file)

            # Add Rule ID if not present
            if ! grep -q "Rule ID:" $file; then
              sed -i "1i ---\nRule ID: UBYX-${id}\nLast Modified: ${last_modified}\n---" $file
              echo "Added Rule ID and Last Modified to $file"
            else
              echo "Rule ID already exists in $file"
            fi

            git add $file
          done

      - name: Commit Changes
        run: |
          git commit -m "Auto-update metadata for rule files" || echo "No changes to commit"
          git push origin HEAD:main
